name = "OpenModelica"
uuid = "4fa5c7c7-00bc-413e-90a6-2009f2bf81d5"
repo = "https://github.com/JKRT/OpenModelicaRegistry.git"
description = "A Julia registry for OpenModelica tooling."

[packages]
0174eeea-c361-11e9-3d0d-a9ca8048aff6 = { name = "DAE", path = "D/DAE" }
350d45b0-c210-11e9-3b9e-fdad65bb3d46 = { name = "SCode", path = "S/SCode" }
53cd29f2-c28d-11e9-1567-bd5452eeb1a0 = { name = "ArrayUtil", path = "A/ArrayUtil" }
ce2f92e2-a952-11e9-0543-8b443f216f1d = { name = "Absyn", path = "A/Absyn" }
