name = "OpenModelica"
uuid = "4fa5c7c7-00bc-413e-90a6-2009f2bf81d5"
repo = "https://github.com/JKRT/OpenModelicaRegistry.git"
description = "A Julia registry for OpenModelica tooling."

[packages]
0174eeea-c361-11e9-3d0d-a9ca8048aff6 = { name = "DAE", path = "D/DAE" }
11f87224-cae7-4e99-a924-e50d12f62c59 = { name = "OMParser", path = "O/OMParser" }
350d45b0-c210-11e9-3b9e-fdad65bb3d46 = { name = "SCode", path = "S/SCode" }
3cc3926e-259e-5855-988e-4819684349c8 = { name = "OpenModelicaParser", path = "O/OpenModelicaParser" }
4a558cac-c1ed-11e9-20da-3584bcd8709a = { name = "ImmutableList", path = "I/ImmutableList" }
53cd29f2-c28d-11e9-1567-bd5452eeb1a0 = { name = "ArrayUtil", path = "A/ArrayUtil" }
9d7f2a79-07b5-5542-8b19-c0100dda6b06 = { name = "MetaModelica", path = "M/MetaModelica" }
b10394b5-f439-4073-a0c5-e09cb00cf46c = { name = "OMFrontend", path = "O/OMFrontend" }
b2a72b7e-c1ef-11e9-3a87-6ddc5900c366 = { name = "ListUtil", path = "L/ListUtil" }
ce2f92e2-a952-11e9-0543-8b443f216f1d = { name = "Absyn", path = "A/Absyn" }
